import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Star } from 'lucide-react';
import { ImageWithFallback } from './ImageWithFallback';
import { Button } from './Button';
export default function RecommendedDishes({ dishes, onRate, }) {
    if (!dishes || dishes.length === 0)
        return null;
    return (_jsxs("section", { children: [_jsx("h3", { className: "text-lg font-semibold mb-3", children: "Recommended Dishes" }), _jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4", children: dishes.map((d) => (_jsxs("div", { className: "border rounded-lg overflow-hidden bg-white", children: [d.photoUrl ? (_jsx(ImageWithFallback, { src: d.photoUrl, alt: d.name, className: "w-full h-36 object-cover" })) : (_jsx("div", { className: "w-full h-36 bg-gray-100 flex items-center justify-center", children: "No image" })), _jsxs("div", { className: "p-3", children: [_jsxs("div", { className: "flex items-start justify-between gap-2", children: [_jsxs("div", { className: "flex-1", children: [_jsx("div", { className: "font-medium text-sm truncate", children: d.name }), d.description && _jsx("div", { className: "text-xs text-gray-600", children: d.description })] }), _jsxs("div", { className: "text-right", children: [_jsxs("div", { className: "flex items-center gap-1 text-sm", children: [_jsx(Star, { className: "h-4 w-4 text-yellow-400 fill-yellow-400" }), _jsx("span", { className: "text-sm", children: d.averageRating.toFixed(1) })] }), _jsxs("div", { className: "text-xs text-gray-500", children: [d.ratingCount, " rating", d.ratingCount === 1 ? '' : 's'] })] })] }), _jsxs("div", { className: "mt-3 flex items-center gap-2", children: [_jsx(Button, { size: "sm", onClick: () => onRate && onRate(d.id, 5), children: "Rate 5" }), _jsx(Button, { variant: "ghost", size: "sm", onClick: () => onRate && onRate(d.id, 4), children: "Rate 4" }), _jsx("div", { className: "ml-auto text-xs text-gray-600", children: d.priceCents ? `$${(d.priceCents / 100).toFixed(2)}` : '' })] })] })] }, d.id))) })] }));
}
